Simple Vec128b implementation
vsinitsynav/vec-lib pull request #1
Opened 2024-01-30 19:52 UTC by vsinitsynav

2024-01-31 13:33 UTC, asokol123 requested changes

2024-01-31 13:33 UTC, asokol123 commented on src/vectori128.rs
> +    pub const fn build(x: __m128i) -> Self {
Давай делать публичный интерфейс вообще без `__m128i`
Эту неудобная структура специально для simd, и внешний пользователь про нее не хочет думать
Можно либо `pub(crate)`, если это чисто внутри библиотеки будет пользоваться, либо например массив `[u8; 32]` принимать

2024-01-31 13:33 UTC, asokol123 commented on src/vectori128.rs
> +    pub unsafe fn load_a(&mut self, mem_addr: *const __m128i) {
Лучше назвать `load_aligned`
Краткость названия методов уже не так сильно влияет, а понятнее станет сильно
Особенно это актуально для unsafe методов (хотя и не только)

2024-01-31 13:33 UTC, asokol123 commented on src/vectori128.rs
> +    pub unsafe fn store_nt(&self, mem_addr: *mut __m128i) {
Тут по названию я вообще не понимаю что это

2024-01-31 13:33 UTC, asokol123 commented on src/vectori128.rs
> +    pub fn size(&self) -> usize {
А почему не ассоциированной константой?
И в расте чаще называют len, чем size скорее

2024-01-31 13:33 UTC, asokol123 commented on tests/test_veci128.rs
> +fn test_vec128b() {
Такие простые тесты чаще пишут прямо в конце файла в модуле tests, но не принципиально, тут как тебе больше нравится

2024-01-31 13:33 UTC, asokol123 commented on src/lib.rs
> +pub mod vectori128;
Надо сделать так, чтобы этот модуль был доступен только если все инструкции, исплользующиеся в нем, доступны (через cfg проверку уровня инструкций процессора)
Если проверка сложная получается, можно посмотреть на крейт [cfg_aliases](https://docs.rs/cfg_aliases/latest/cfg_aliases/) и build.rs

2024-02-12 16:32 UTC, asokol123 requested changes

2024-02-12 16:32 UTC, asokol123 commented on src/vectori128.rs
> +    pub unsafe fn load(&mut self, mem_addr: *const u8) -> &Self {
А зачем тут возвращать `&Self`?
В расте, кажется, не принято (по крайней мере ни разу не видел похожего, за исключением builder pattern)
И почему не `&mut Self` тогда?

2024-02-12 16:32 UTC, asokol123 commented on src/lib.rs
> +#[cfg(target_arch = "x86_64")]
Скорее надо что-то вроде `cfg(target_feature = "sse")`
Но сначала надо убедиться, что все использованные инструкции входят в sse

2024-02-12 16:32 UTC, asokol123 commented on src/vectori128.rs
> +    /// You may use load_aligned instead of load if you are certain that
Лучше `mem_addr must be aligned by 16 bytes`, или что-то похожее
Намного короче, а смысл тот же

Это особенно пригождается на работе, когда чтение документации и кода занимают 80% времени, и начинаешь ценить короткие осмысленные предложения

2024-02-12 16:32 UTC, asokol123 commented on src/vectori128.rs
> +    pub const fn len(&self) -> usize {
Лучше `pub const LEN: usize = 128`

2024-02-12 16:32 UTC, asokol123 commented on src/vectori128.rs
> +    #[inline]
А на методы тогда `#[inline]` не нужен?

2024-02-12 16:32 UTC, asokol123 commented on src/vectori128.rs
> +pub unsafe fn andnot(a: Vec128b, b: Vec128b) -> Vec128b {
А почему это `unsafe`?

И не лучше сделать методом?
Второе - именно вопрос, я сам не знаю, что из этого лучше
```rust
andnot(a, b);
a.andnot(b);
```

2024-02-12 16:32 UTC, asokol123 commented on src/vectori128.rs
> +pub unsafe fn selectb(s: __m128i, a: __m128i, b: __m128i) -> __m128i {
Аналогично, почему это `unsafe`?
Кажется, вызов всегда безопасен (если нужные инструкции есть)

2024-02-12 16:32 UTC, asokol123 commented on src/vectori128.rs
> +pub unsafe fn selectb(s: __m128i, a: __m128i, b: __m128i) -> __m128i {
И почему в сигнатуре `__m128i`, а не `Vec128b`?

2024-02-12 16:32 UTC, asokol123 commented on src/vectori128.rs
> +#[test]
Тесты лучше выносить в модуль:
```rust
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_vec128b() {}
}
```
Это нужно чтобы тесты компилировались только тогда, когда мы запускаем `cargo test`, и не компилировались при обычном `cargo build`

2024-02-12 19:39 UTC, vsinitsynav commented on src/vectori128.rs
> +pub unsafe fn selectb(s: __m128i, a: __m128i, b: __m128i) -> __m128i {
В VCL данная функция является вспомогательной и используется в реализации других классов. Кажется стоит убрать из сигнатуры `pub`

2024-02-12 19:47 UTC, asokol123 commented on src/vectori128.rs
> +pub unsafe fn selectb(s: __m128i, a: __m128i, b: __m128i) -> __m128i {
Или сделать `pub(crate)` чтобы была доступна и в других модулях, но только внутри твоего крейта, и не внешним пользователям

2024-04-16 10:22 UTC, asokol123 requested changes

2024-04-16 10:22 UTC, asokol123 commented on src/vectori128.rs
> +    unsafe {
Перед каждым `unsafe` блоком должен быть SAFETY-комментарий, объясняющий (можно в двух словах), почему тут не будет UB

2024-04-16 10:22 UTC, asokol123 commented on src/vectori128.rs
> +///# Safety
А тут будет UB если s будет содержать плохие байты? Если да, то функцию надо пометить `unsafe` (даже при том, что она только `pub(crate)`)

2024-04-24 11:24 UTC, merged