Vec16c
vsinitsynav/vec-lib pull request #2
Opened 2024-04-24 12:42 UTC by vsinitsynav

2024-04-27 18:01 UTC, asokol123 requested changes

2024-04-27 18:01 UTC, asokol123 commented on Cargo.toml
> +criterion-plot = "0.5.0"
А почему это все не `dev-dependencies`?

2024-04-27 18:01 UTC, asokol123 commented on benches/vec16c_benchmark.rs
> +use rand::Rng; // 0.6.5
Комментарий явно лишний
Плюс может в будущем ввести в заблуждение если обновишь версию `rand`, а тут забудешь

2024-04-27 18:01 UTC, asokol123 commented on benches/vec16c_benchmark.rs
> +fn stupid(a: &Vec<i8>, b: &Vec<i8>) {
надо принимать `&[i8]`
в чем разница:
1) `&[i8]` более general - ты можешь передать ссылку на массив, или на какой-то кусок массива/вектора, и все сработает
2) лишняя индирекция: если ты принимаешь `&Vec<i8>`, то ты получаешь ссылку (по сути указатель) на структуру из 3 полей. Таким образом чтобы получить доступ к элементу. надо сначала пройти по первому указателю, прочитать данные вектора, и пройти по второму указателю оттуда (сумбурно объяснил, если не до конца понятно или есть вопросы - пиши)

2024-04-27 18:01 UTC, asokol123 commented on benches/vec16c_benchmark.rs
> +        c[i] = black_box(a[i] * b[i]);
У тебя сейчас `black_box` навешен на одно конкретное умножение
А бенчмаркать лучше более крупные функции - например написать функцию `fn stupid(a: &[i8], b: &[i8], c: &mut [i8])` (или возвращать вектор, +- пофиг), и сравнивать так: `stupid(black_box(&a), black_box(&b))`

2024-04-27 18:01 UTC, asokol123 commented on benches/vec16c_benchmark.rs
> +        unsafe {
Добавь проверок на соответствие размеров. У тебя тут UB на UB если вдруг налажать с размерами.

И лучше не делать тут такой большой `unsafe` блок, а делать маленький вокруг каждой операции
И перед каждым `unsafe` блоком должен быть (хотя бы краткий) комментарий, почему это безопасно (можно в формате `/// SAFETY: obviously`)

2024-04-27 18:01 UTC, asokol123 commented on benches/vec16c_benchmark.rs
> +criterion_main!(benches);
Перенос строки в конце файла

2024-04-27 18:01 UTC, asokol123 commented on benches/vec16c_benchmark.rs
> +// criterion_group!(benches, multiplication_benchmark);
..а почему комментарий, и ниже точно такая же строчка? и в целом почему код в комментарии

2024-04-27 18:01 UTC, asokol123 commented on benches/vec16c_benchmark.rs
> +    let a: Vec<i8> = (0..1000000).map(|_| rng.gen_range(0..11)).collect();
`0..LEN`?

2024-04-27 18:01 UTC, asokol123 commented on src/vectori128.rs
> +///# Safety: each byte in s must be either 0 (false) or 0xFF (true).
Вот, тут правильный SAFETY комментарий перед функцией. Ты тут описываешь что должен соблюдать вызывающий, а не почему она небезопасна. Такой должен быть и перед всем остальными.

2024-04-27 18:01 UTC, asokol123 commented on src/vectori128.rs
> +    pub fn set_values(
Ужас какой. Почему не принимать `[i8; 16]`?

2024-04-27 18:01 UTC, asokol123 commented on src/vectori128.rs
> +    pub unsafe fn load_partial(&mut self, n: isize, mem_addr: *const i8) {
А почему эта функция принимает не `&[i8]`?
Кажется, это ровно пара (указатель; размер), при этом память под этим указателем валидна на такой размер. заодно от unsafe можно будет избавиться

2024-04-27 18:01 UTC, asokol123 commented on src/vectori128.rs
> +            self.load(&x as *const i8);
Выглядит ооочень плохо. То есть у функции `load` требование чтобы данные не пересекали границу страницы? А почему? И тогда пользователю придется каждый раз перед вызовом это проверять?

2024-04-27 18:01 UTC, asokol123 commented on src/vectori128.rs
> +        if n as u32 >= 16 {
А если передадут отрицательное? Кажется, тогда будет неправильно. И почему вообще n: isize, а не usize тогда?

2024-04-27 18:01 UTC, asokol123 commented on src/vectori128.rs
> +            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0,
А лучше не написать? Тут именно спрашиваю, не знаю, можно ли лучше, хочется что-то типа `[-1; N] + [0; N]`

2024-04-27 18:01 UTC, asokol123 commented on src/vectori128.rs
> +/// for (int i = 0; i < 16; i++) result[i] = s[i] ? a[i] : b[i];
А не хотим здесь написать [doctest](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html)?

2024-05-09 12:24 UTC, vsinitsynav commented on benches/vec16c_benchmark.rs
> +fn stupid(a: &Vec<i8>, b: &Vec<i8>) {
Кажется при создании массива размера порядка 1e7 происходит переполнение стека, с вектором такой проблемы не было

2024-05-09 12:40 UTC, vsinitsynav commented on benches/vec16c_benchmark.rs
> +        unsafe {
А есть возможность как-то сделать проверку, что выделено хотя бы SIZE байт памяти, если в сигнатуре будет &[i8]?

2024-05-09 12:55 UTC, asokol123 commented on benches/vec16c_benchmark.rs
> +fn stupid(a: &Vec<i8>, b: &Vec<i8>) {
Ты можешь передать `&Vec<T>` в функцию, которая ожидает `&[T]`
`&[T]` - слайс подряд идущих данных. Не важно, массив, вектор, другая магия - все работать будет.

Вектор передать сюда можно потому что есть `impl<T> Defef<Target = [T]> for Vec<T>`

2024-05-09 12:56 UTC, asokol123 commented on benches/vec16c_benchmark.rs
> +        unsafe {
На этапе компиляции - нету

2024-05-10 08:09 UTC, merged